plugins { id 'com.android.application' }

android {
    namespace 'dev.mich.quotile'
    compileSdk 36
    defaultConfig {
        applicationId 'dev.mich.quotile'
        minSdk 31
        targetSdk 36
        versionCode 10
        versionName '0.3.7'
        testInstrumentationRunner 'dev.mich.quotile.ManualModeTests'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}
